# Generated by Django 6.0.7 on 2026-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_student_course_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qr_code_path',
        ),
        migrations.AddField(
            model_name='student',
            name='application_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
